modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="${project.name}"
version="${file.jarVersion}"

displayName="Mod"

# updateJSONURL="https://curseforge.com/minecraft/mc-mods/mod"
# displayURL="http://example.com/"
# logoFile="mod.png"

# credits="Thanks for this example mod goes to Java"
authors="author"

description='''
-Desc-
'''

[[dependencies.modid]]
   modId="forge"
   versionRange="[36,)"

   ordering="NONE"
   side="BOTH"

   mandatory=true

[[dependencies.modid]]
   modId="minecraft"
   versionRange="[1.16.5,1.17)"

   ordering="NONE"
   side="BOTH"

   mandatory=true
